name: yx_scope_flutter_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yx_scope_flutter:
    path: ../
  yx_scope: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.6.8
  yx_scope_linter: ^0.1.0

flutter:
  uses-material-design: true
