name: yx_scope_example
description: "An example for yx_scope"
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  yx_scope:
    path: ..

dev_dependencies:
  lints: ^2.0.1
